events {}

http {
    include       /etc/nginx/mime.types;  # Incluye los tipos MIME estándar
    default_type  application/octet-stream;

    server {
        listen 80;
        server_name localhost;

        location / {
            # Cambia la ruta raíz al directorio donde copiaste los archivos de la app
            root /var/www/html;
            index index.html index.htm;

            # Intenta servir los archivos estáticos y, si no existen, redirige a index.html (útil para SPAs)
            try_files $uri $uri/ /index.html;
        }
    }
}
