version: '3'

services:
  app-backend:
    container_name: backend
    image: m2gargu/back_warwiki40k:back_warwiki40k
    ports:
      - "8000:80"
    restart: always
  
  app-frontend:
    container_name: frontend
    image: m2gargu/front_warwiki40k:front_warwiki40k
    ports:
      - "80:80"
    depends_on:
      - app-backend
    restart: always
    