<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SoldierSeeder extends Seeder
{
    private $soldiers = [
        #region Novitiates
        [
            'name' => "Novitiate Militant",
            'image' => 'novitiate_militant.jpg',
            //
            'description' => 'Las Novitiates Militant son hermanas de batalla en entrenamiento. Todavía tienen que ganarse la servoarmadura y los bólteres de las Hermanas de Batalla de pleno derecho, pero de todos modos son celosos guerreros del Emperador, ansiosos por unirse a las filas de su Orden Militante.',
            'squadron_id' => 1,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "4+",
            'w' => 7,
            'base' => '28mm',
        ],
        [
            'name' => "Novitiate Superior",
            'image' => 'novitiate_superior.jpg',
            //
            'description' => 'Una Novitiate Superior, una Hermana de Batalla de pleno derecho de una Orden Militante, tiene la tarea de liderar a las Novitiates en la batalla. Toman decisiones de mando, dirigen la fe de sus pupilos y sirven como ejemplos inspiradores de cómo actúa un guerrero del Adepta Sororitas en todo momento.',
            'squadron_id' => 1,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "3+",
            'w' => 8,
            'base' => '32mm',
        ],
        [
            'name' => "Novitiate Penitent",
            'image' => 'novitiate_penitent.jpg',
            //
            'description' => 'A algunas Novitiate se les ordena empuñar brutales evisceradores como señal de vergüenza por transgresiones menores. Instadas a ganar su redención cara a cara con el enemigo, estas Hermanas lucharán con furia desenfrenada para recuperar su honor.',
            'squadron_id' => 1,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "4+",
            'w' => 7,
            'base' => '28mm',
        ],
        [
            'name' => "Novitiate Purgatur",
            'image' => 'novitiate_purgatur.jpg',
            //
            'description' => 'Las Novitiate Purgatus tienen el santo deber de llevar la llama purificadora a los enemigos de la Humanidad. Cuando desatan sus lanzallamas Ministorum contra el enemigo, dejan poco más que cenizas.',
            'squadron_id' => 1,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "4+",
            'w' => 7,
            'base' => '28mm',
        ],
        [
            'name' => "Novitiate Pronatus",
            'image' => 'novitiate_pronatus.jpg',
            //
            'description' => 'Para servir en las Órdenes Pronatus, un candidato debe aprender todo lo que hay que saber sobre innumerables tipos de reliquias, además de ser guerreros altamente capacitados. Se espera que recuperen y protejan artefactos muy valiosos y, a veces, extremadamente peligrosos.',
            'squadron_id' => 1,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "4+",
            'w' => 7,
            'base' => '28mm',
        ],
        [
            'name' => "Novitiate Exactor",
            'image' => 'novitiate_exactor.jpg',
            //
            'description' => 'A algunas Novitiate celosas se les dan látigos neuronales con los que infligir angustia física y mental al enemigo. En ocasiones, la portadora utilizará estas armas contra compañeras Novitiate que considere que carecen de compromiso y que necesitan ser disuadidos de cometer errores de valentía y fe.',
            'squadron_id' => 1,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "4+",
            'w' => 7,
            'base' => '28mm',
        ],
        [
            'name' => "Novitiate Reliquarius",
            'image' => 'novitiate_reliquarius.jpg',
            //
            'description' => 'Algunas Novitiate llevan íconos inspiradores, como un tapiz ornamentado, un relicario que contiene los restos mortales de un santo o un simulacro de un artefacto famoso. Las Novitiate que contemplan tales reliquias saben que el poder sagrado del Dios Emperador está con ellas y luchan con más ahínco por conseguirlo.',
            'squadron_id' => 1,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "4+",
            'w' => 8,
            'base' => '28mm',
        ],
        [
            'name' => "Novitiate Hospitaller",
            'image' => 'novitiate_hospitaller.jpg',
            //
            'description' => 'Curar los males físicos y espirituales de los heridos en el campo de batalla del Imperio es una tarea onerosa, que requiere innumerables horas de práctica. Las Novitiate que buscan ser admitidas en las Órdenes Hospitaller perfeccionan sus habilidades en el campo, ayudando a sus compañeras Novitiate en todo lo que puedan.',
            'squadron_id' => 1,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "4+",
            'w' => 7,
            'base' => '28mm',
        ],
        [
            'name' => "Novitiate Preceptor",
            'image' => 'novitiate_preceptor.jpg',
            //
            'description' => 'Se espera que estas Novitiate hagan cumplir rígidamente los preceptos de su Orden, asegurando que sus compañeras cumplan fielmente las normas prescritas. A menudo son elegidas como segundos al mando de su Superior y sirven como ejemplo al entrar con entusiasmo en la refriega para derrotar a los enemigos del Emperador.',
            'squadron_id' => 1,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "4+",
            'w' => 7,
            'base' => '28mm',
        ],
        [
            'name' => "Novitiate Dialogus",
            'image' => 'novitiate_dialogus.jpg',
            //
            'description' => 'Estas Novitiate están entrenándose para unirse a Orders Dialogus, mientras aprenden la guerra bajo la guía de Hermanas de Batalla experimentadas. Su formación en criptografía las hace de gran valor para matar equipos: pueden desbloquear cifrados oscuros y encontrar patrones ocultos en comunicados.',
            'squadron_id' => 1,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "4+",
            'w' => 7,
            'base' => '28mm',
        ],
        [
            'name' => "Novitiate Duellist",
            'image' => 'novitiate_duellist.jpg',
            //
            'description' => 'Algunas Novitiate tienen una afinidad natural por el trabajo con espadas, y sus tiempos de reacción y destreza son mayores que los de sus compañeras guerreras. Salen al campo ansiosas por demostrar su habilidad, deseando reclamar las cabezas de los enemigos más capaces y emular a los guerreros o santos de la leyenda.',
            'squadron_id' => 1,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "4+",
            'w' => 7,
            'base' => '28mm',
        ],
        [
            'name' => "Novitiate Condemnor",
            'image' => 'novitiate_condemnor.jpg',
            //
            'description' => 'Los hechiceros y las brujas se encuentran entre los enemigos más odiados del Adepta Sororitas. Estas abominaciones psíquicas son amenazas terribles para el reino del Emperador, y acabar con ellas es una prioridad clave. Las Novitiate Condemnor están especialmente equipadas para hacer frente a este tipo de enemigos.',
            'squadron_id' => 1,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "4+",
            'w' => 7,
            'base' => '28mm',
        ],
        #endregion
        #region Eluicidian Startrider
        [
            'name' => "Elucia Vhane",
            'image' => 'elucia_vhane.jpg',
            //
            'description' => 'Una vez maestra del Nuevo Amanecer, la comerciante independiente Elucia Vhane proviene de una antigua dinastía. Su formación familiar perfeccionó su liderazgo innato y empuña su bastón estoque, Blur, como una maestra duelista. Siempre está atento a los enemigos a través de un auspicador multiespectral.',
            'squadron_id' => 2,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "4+",
            'w' => 8,
            'base' => '25mm',
        ],
        [
            'name' => "Canid",
            'image' => 'canid.jpg',
            //
            'description' => 'Se crían o cultivan en cubas innumerables variedades de cánidos para cumplir funciones de caza, ataque o intimidación, y muchos comerciantes independientes aprecian la combinación de lealtad y agresión. Elucia Vhane llamó a su bestia Aximillion, sus hombres del Vacío la entrenaron como guardiana y compañera.',
            'squadron_id' => 2,
            'm' => "4 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "5+",
            'w' => 6,
            'base' => '25mm',
        ],
        [
            'name' => "Death Cult Executioner",
            'image' => 'death_cult_executioner.jpg',
            //
            'description' => 'Para un Death Cult Executioner, el acto de vivir es una blasfemia que sólo se equilibra con la cantidad de almas que cosecha. Entregan la muerte de cerca y dominan numerosos estilos de combate. Un seguidor de Vhane, el Death Cult Executioner, Knosso Prond, ha prometido matar a mil xenos diferentes.',
            'squadron_id' => 2,
            'm' => "3 2Circles",
            'apl' => 3,
            'ga' => 1,
            'df' => 3,
            'sv' => "6+",
            'w' => 8,
            'base' => '25mm',
        ],
        [
            'name' => "Letro-Maester",
            'image' => 'letro_maester.jpg',
            //
            'description' => 'Al albergar una conexión con la Fuerza Motriz, estos Tecnosacerdotes son seguidores del Culto Mechanicus, capaces de generar un campo voltagheist protector a partir del mecanismo en su espalda. El Lectro-Maester Larsen van der Grauss se unió a las exploraciones de Vhane en busca de descubrimientos esotéricos.',
            'squadron_id' => 2,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "4+",
            'w' => 8,
            'base' => '25mm',
        ],
        [
            'name' => "Rejuvenat Adept",
            'image' => 'rejuvenat_adept.jpg',
            //
            'description' => 'Estos agentes son maestros de la curación y la longevidad. Proporcionan agentes anestésicos y cirugía de emergencia, incluso en los entornos más horribles. Rejuvenat Adept Sanistasia Minst se unió a los Starstriders en su búsqueda obsesiva de una panacea.',
            'squadron_id' => 2,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "5+",
            'w' => 7,
            'base' => '25mm',
        ],
        [
            'name' => "Voidmaster",
            'image' => 'voidmaster.jpg',
            //
            'description' => 'Los Voidmaster lideran escuadrones de soldados navales. Ladrando órdenes para garantizar la disciplina en el fuego, su cumplimiento de los códigos navales es inquebrantable. El Voidmaster Nitsch y su escuadrón fueron enviados a Vhane desde el buque de guerra Vengeance, y su valentía bajo el fuego es legendaria.',
            'squadron_id' => 2,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "5+",
            'w' => 8,
            'base' => '25mm',
        ],
        [
            'name' => "Voidsman",
            'image' => 'voidsman.jpg',
            //
            'description' => 'Los Voidsman suelen servir en buques de guerra, matando a cualquiera que amenace su nave o su tripulación. Ceñidos con una armadura barroca, mantienen a raya a los enemigos con disparos láser. Entre el escuadrón de Voidmaster Nitsch, el veterano Stromian Grell lleva un cañón de rotor gracias a sus consistentes patrones de disparo.',
            'squadron_id' => 2,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "5+",
            'w' => 7,
            'base' => '25mm',
        ],
        #endregion
        #region Exaction Squad
        [
            'name' => "Arbites Proctor-Exactant",
            'image' => 'arbites_proctor_exactant.jpg',
            //
            'description' => 'Los Exaction Squad son seleccionados y dirigidos por Proctors-exactant. Estos árbitros experimentados son tácticos despiadados y luchadores inteligentes. También son encarnaciones intimidantes de la justicia imperial y emplean nuncio-aquilas para transmitir discursos ensordecedores que intimidan a los culpables para que se sometan.',
            'squadron_id' => 3,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "4+",
            'w' => 9,
            'base' => '28mm',
        ],
        [
            'name' => "Arbites Castigator",
            'image' => 'arbites_castigator.jpg',
            //
            'description' => 'El papel del Arbites Castigator es garantizar que los culpables reciban el castigo debido, y sus yelmos con forma de capucha fortalecen su determinación contra maldiciones y súplicas por igual. Una vez localizada la cantera, los Castigator se encargan de someterlos por cualquier medio, una tarea que realizan con celosa dedicación.',
            'squadron_id' => 3,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "4+",
            'w' => 8,
            'base' => '28mm',
        ],
        [
            'name' => "Arbites Chirurgant",
            'image' => 'arbites_chirurgant.jpg',
            //
            'description' => 'Estos Arbites son especialistas médicos altamente calificados, acostumbrados a tratar heridas debilitantes infligidas por quienes se resisten a la detención. También son expertos en el interrogatorio táctico de prisioneros y han estudiado los límites hasta los cuales se puede empujar el cuerpo para obtener respuestas.',
            'squadron_id' => 3,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "4+",
            'w' => 8,
            'base' => '28mm',
        ],
        [
            'name' => "Arbites Gunner",
            'image' => 'arbites_gunner.jpg',
            //
            'description' => 'Los Arbites Gunner proporcionan una potencia de fuego sustancial a las operaciones del Exaction Squad utilizando armas como ametralladoras pesadas: cañones de disparo rápido cuyo disparo sólido puede atravesar a las turbas. Las armas más especializadas pueden disparar sustancias químicas que paralizan o granadas que abren puertas y armaduras por igual.',
            'squadron_id' => 3,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "4+",
            'w' => 8,
            'base' => '28mm',
        ],
        [
            'name' => "Arbites Leashmaster",
            'image' => 'arbites_leashmaster.jpg',
            //
            'description' => 'Los Leashmasters son especialistas que dirigen a los servidores caniformes conocidos como Cyber-mastiffs. Anulan directamente los protocolos básicos de la construcción con comandos avanzados y transmiten órdenes a gritos a su presa acosada por la culpa a través de los emisores del Cyber-mastiff.',
            'squadron_id' => 3,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "4+",
            'w' => 8,
            'base' => '28mm',
        ],
        [
            'name' => "R-VR Cyber-mastiff",
            'image' => 'r_vr_cyber_mastiff.jpg',
            //
            'description' => 'Los Arbitrators emplean muchas servoconstrucciones para intimidación, seguridad y persecución. El Venatus Reclamotor clase Rantal es un Cyber-mastiff avanzado utilizado por los Escuadrones de Exacción. Los detectores del R-VR les permiten rastrear a sus presas, mientras que sus mandíbulas de hierro pueden romper huesos o matar cuando se les ordena.',
            'squadron_id' => 3,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "4+",
            'w' => 8,
            'base' => '25mm',
        ],
        [
            'name' => "Arbites Malocator",
            'image' => 'arbites_malocator.jpg',
            //
            'description' => 'Técnicamente dotados, los Malocators llevan extractores de muestras biológicas para recopilar evidencia de rastros en la cantera de su equipo. Operan con una calma helada bajo el fuego, examinando pruebas a través de su conjunto veriscante de múltiples lentes e informando a su equipo sobre las debilidades del enemigo.',
            'squadron_id' => 3,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "4+",
            'w' => 8,
            'base' => '28mm',
        ],
        [
            'name' => "Arbites Marksman",
            'image' => 'arbites_marksman.jpg',
            //
            'description' => 'El agitador que se esconde detrás de aquellos a quienes incita, el guardaespaldas fuertemente armado o el criminal que huye y está a punto de escapar: tales son los objetivos del Marksman. Sus escopetas de cañón largo disparan proyectiles tan potentes que dejan heridas más parecidas a cráteres sangrientos que a agujeros de bala.',
            'squadron_id' => 3,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "4+",
            'w' => 8,
            'base' => '28mm',
        ],
        [
            'name' => "Arbites Revelatum",
            'image' => 'arbites_revelatum.jpg',
            //
            'description' => 'Los Revelatums reconocen los movimientos de su objetivo antes que el resto del equipo, explorando escondites y determinando contactos criminales. Luego guían a otros Arbites directamente hacia los culpables, utilizando sus escáneres de culpa del alma para identificar amenazas a sus compañeros oficiales.',
            'squadron_id' => 3,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "4+",
            'w' => 8,
            'base' => '28mm',
        ],
        [
            'name' => "Arbites Subductor",
            'image' => 'arbites_subductor.jpg',
            //
            'description' => 'Los Arbites Subductor poseen una de las siluetas más reconocibles (y temidas) de las clases criminales del Imperio. Con escudos de asalto con patrón de subyugación y mazos de choque crepitantes, son brutales luchadores de primera línea capaces de aplastar al disidente más obstinado.',
            'squadron_id' => 3,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "3+",
            'w' => 8,
            'base' => '28mm',
        ],
        [
            'name' => "Arbites Vigilant",
            'image' => 'arbites_vigilant.jpg',
            //
            'description' => 'Los Arbites Vigilant barren brutalmente a los culpables con la escopeta de combate característica del Adeptus Arbites. Estos hombres y mujeres sombríos están siempre alerta ante las malas prácticas y son inquebrantables en su castigo, desatando explosiones devastadoras a corta distancia.',
            'squadron_id' => 3,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "4+",
            'w' => 8,
            'base' => '28mm',
        ],
        [
            'name' => "Arbites Vox-Signifier",
            'image' => 'arbites_vox_signifier.jpg',
            //
            'description' => 'El significante Vox-signifier escucha misivas codificadas del comando de misión en su poderoso relé de voz del distrito. Publican actualizaciones para el resto del Exaction Squad a partir de cambios en las prioridades de la misión y nueva inteligencia, probablemente extraída dolorosamente de los prisioneros.',
            'squadron_id' => 3,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "4+",
            'w' => 8,
            'base' => '28mm',
        ],
        #endregion
        #region Imperial Navy Breacher
        [
            'name' => "Navis Sergeant-At-Arms",
            'image' => 'navis_sergeant_at_arms.jpg',
            //
            'description' => 'Como luchadores disciplinados, a menudo con años de experiencia en los mástiles, los líderes de los escuadrones Breacher de la Armada Imperial son tan hábiles en el combate cuerpo a cuerpo como en el diseño de tácticas ganadoras de batallas en movimiento.',
            'squadron_id' => 4,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "4+",
            'w' => 8,
            'base' => '25mm',
        ],
        [
            'name' => "Navis Armsman",
            'image' => 'navis_armsman.jpg',
            //
            'description' => 'Bien entrenados y bien equipados, los equipos de combate de Armsmen del Imperial Navy Breacher son tropas formidables en los estrechos confines del combate barco a barco. Cualquier enemigo al que no puedan derribar con sus poderosas escopetas lo derriban con feroces golpes de sus hachas.',
            'squadron_id' => 4,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 2,
            'df' => 3,
            'sv' => "4+",
            'w' => 7,
            'base' => '25mm',
        ],
        [
            'name' => "Navis Axejack",
            'image' => 'navis_axejack.jpg',
            //
            'description' => 'A veces, la única solución a un problema al que se enfrentan los Breachers de la Armada Imperial es un hacha pesada de dos manos. Los Axejacks que portan estas armas no sólo pueden atravesar obstáculos bloqueados en las puertas, sino que también son luchadores formidables que destrozan a cualquier enemigo en su camino.',
            'squadron_id' => 4,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "4+",
            'w' => 7,
            'base' => '25mm',
        ],
        [
            'name' => "Navis C.A.T. Unit",
            'image' => 'navis_cat_unit.jpg',
            //
            'description' => 'Las Cyber-Altered Task Units son vehículos de reconocimiento con orugas que han servido al Imperio durante milenios. Equipados con equipos de grabación de imágenes y augurios de escaneo de frecuencia, pueden operarse de forma remota para proporcionar información táctica vital para su equipo de ataque.',
            'squadron_id' => 4,
            'm' => "4 2Circles",
            'apl' => 1,
            'ga' => 1,
            'df' => 2,
            'sv' => "5+",
            'w' => 5,
            'base' => '25mm',
        ],
        [
            'name' => "Navis Endurant",
            'image' => 'navis_endurant.jpg',
            //
            'description' => 'Sólo los soldados más grandes de un escuadrón pasan a ser conocidos como Endurants. A ellos les corresponde la tarea de llevar un escudo Endurant y una escopeta pesada mientras apuntan o protegen la retaguardia del escuadrón. Su gran tamaño los hace muy intimidantes para sus enemigos.',
            'squadron_id' => 4,
            'm' => "2 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "2+",
            'w' => 10,
            'base' => '28mm',
        ],
        [
            'name' => "Navis Gheistskull",
            'image' => 'navis_gheistskull.jpg',
            //
            'description' => 'Estos servocráneos suelen estar hechos de cabezas de antiguos Breachers de la Armada Imperial. Como resultado, a menudo se les llama "La venganza del hombre muerto" o se los considera la "Última risa" del soldado fallecido por su capacidad para detonar y matar a todos los que los rodean en un acto final de desafío hacia el enemigo.',
            'squadron_id' => 4,
            'm' => "4 2Circles",
            'apl' => 1,
            'ga' => 1,
            'df' => 2,
            'sv' => "5+",
            'w' => 5,
            'base' => '25mm',
        ],
        [
            'name' => "Navis Grenadier",
            'image' => 'navis_grenadier.jpg',
            //
            'description' => 'La vida de un Breacher de la Armada Imperial es acostumbrarse a las explosiones. Más aún para los Grenadier. Estos soldados llevan cargas de demolición diseñadas para atravesar mamparos y puertas selladas, lo que permite a sus compañeros de escuadrón seguir moviéndose y alcanzar sus objetivos.',
            'squadron_id' => 4,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "4+",
            'w' => 7,
            'base' => '25mm',
        ],
        [
            'name' => "Navis Gunner",
            'image' => 'navis_gunner.jpg',
            //
            'description' => 'Las tropas más grandes del escuadrón que no cumplen el papel de Endurants llevan las armas a distancia más pesadas de su escuadrón. Una descarga láser desata salvas devastadoras, el calor abrasador de un disparo de pistola de fusión quema a través de un mamparo reforzado e incluso los enemigos fuertemente blindados no pueden resistir una pistola de plasma.',
            'squadron_id' => 4,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "4+",
            'w' => 8,
            'base' => '28mm',
        ],
        [
            'name' => "Navis Hatchcutter",
            'image' => 'navis_hatchcutter.jpg',
            //
            'description' => 'Es vital para los Breachers de la Armada Imperial poder moverse rápidamente a través de los barcos enemigos para alcanzar sus objetivos. Los Hatchcutters no sólo pueden atravesar barricadas con sus puños de cadena y antorchas de plasma, sino que también pueden usar estas últimas para sellar caminos que el enemigo podría usar de otro modo.',
            'squadron_id' => 4,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "4+",
            'w' => 7,
            'base' => '25mm',
        ],
        [
            'name' => "Navis Surveyor",
            'image' => 'navis_surveyor.jpg',
            //
            'description' => 'Saber lo que hay a la vuelta de la esquina puede significar vida o muerte para los Breachers de la Armada Imperial. Al utilizar un C.A.T. unidad, que es capaz de navegar por túneles y agujeros estrechos, un Surveyor puede investigar y preparar su escuadrón para lo que podría venir.',
            'squadron_id' => 4,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "4+",
            'w' => 7,
            'base' => '25mm',
        ],
        [
            'name' => "Navis Void-Jammer",
            'image' => 'navis_void_jammer.jpg',
            //
            'description' => 'Corresponde a los Void-Jammers en un equipo de combate Breacher de la Armada Imperial operar los gheistskulls, servocráneos equipados con un dispositivo explosivo y un emisor de pulsos electromagnéticos. Estos dispositivos pueden moverse rápidamente, volar por el aire y navegar por terrenos demasiado densos para que los Armsmen puedan alcanzar al enemigo.',
            'squadron_id' => 4,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "4+",
            'w' => 7,
            'base' => '25mm',
        ],
        #endregion
        #region Inquisitorial Agents
        [
            'name' => "Interrogator Agent",
            'image' => 'interrogator_agent.jpg',
            //
            'description' => 'Despiadados, ingeniosos y hábiles en todo tipo de habilidades clandestinas y bélicas, los Interrogator son seleccionados por el Inquisidor al que sirven por su tenaz determinación y lealtad inquebrantable, y están en camino de convertirse ellos mismos en Inquisidores.',
            'squadron_id' => 5,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 2,
            'df' => 3,
            'sv' => "5+",
            'w' => 8,
            'base' => '25mm',
        ],
        [
            'name' => "Tome-Skull",
            'image' => 'tome_skull.jpg',
            //
            'description' => 'Estos familiares son servocráneos especializados diseñados para asegurar y mantener abierto un volumen preciado. Los libros elegidos por los Interrogadores para que un Tome-Skull los lleve al campo están impregnados de poder sagrado y llenos de conocimientos arcanos, santificando la tierra y renunciando a los espíritus demoníacos.',
            'squadron_id' => 5,
            'm' => "3 2Circles",
            'apl' => 1,
            'ga' => 2,
            'df' => 2,
            'sv' => "5+",
            'w' => 5,
            'base' => '25mm',
        ],
        [
            'name' => "Autosavant Agent",
            'image' => 'autosavant_agent.jpg',
            //
            'description' => 'Pocos restos quedan del Humano original que alguna vez fue el Autosavant. Gran parte de su forma ha sido reemplazada por biónica dedicada al registro de información. Ya sea en su base de operaciones o en el fragor de la batalla, nunca dejan de escribir cada palabra y hecho que presencian.',
            'squadron_id' => 5,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "4+",
            'w' => 7,
            'base' => '25mm',
        ],
        [
            'name' => "Questkeeper Agent",
            'image' => 'questkeeper_agent.jpg',
            //
            'description' => 'Los Questkeeper, conocidos también como Caballeros Andantes, Penitentes y muchos otros nombres, son fanáticos dedicados al Credo Imperial. Con un odio intenso hacia los enemigos del Emperador, ejecutan misiones juradas para masacrar a herejes y traidores.',
            'squadron_id' => 5,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "5+",
            'w' => 7,
            'base' => '25mm',
        ],
        [
            'name' => "Death World Veteran Agent",
            'image' => 'death_world_veteran_agent.jpg',
            //
            'description' => 'Todo Inquisidor sabe que los mundos de la muerte producen los soldados más duros del Imperio. Muchos hacen todo lo posible para reclutar a Death World Veterans, ya que las habilidades de lucha de estos guerreros son vitales para cazar al hereje.',
            'squadron_id' => 5,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "4+",
            'w' => 1,
            'base' => '25mm',
        ],
        [
            'name' => "Enlightener Agent",
            'image' => 'enlightener_agent.jpg',
            //
            'description' => 'Conocidos por algunos como Excruciators o Truth-Peelers, estos sádicos individuos son muy valorados por los Inquisidores por su total falta de piedad y su asombrosa habilidad para extraer información valiosa, incluso de los prisioneros menos cooperativos.',
            'squadron_id' => 5,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "5+",
            'w' => 7,
            'base' => '25mm',
        ],
        [
            'name' => "Gun Servitor",
            'image' => 'gun_servitor.jpg',
            //
            'description' => 'Más máquinas que humanos, los Gun Servitors son comunes en todo el Imperio y están lobotomizados hasta el punto de carecer de cualquier tipo de capacidad de pensamiento independiente. Utilizados para realizar tareas mundanas y difíciles, transportan cargas pesadas que a menudo incluyen armas pesadas.',
            'squadron_id' => 5,
            'm' => "3 2Circles",
            'apl' => 1,
            'ga' => 1,
            'df' => 3,
            'sv' => "4+",
            'w' => 11,
            'base' => '32mm',
        ],
        [
            'name' => "Hexorcist Agent",
            'image' => 'hexorcist_agent.jpg',
            //
            'description' => 'Los Hexorcists son hombres y mujeres santos que los no iniciados suelen confundir con sacerdotes. Creen que la Fe Imperial sólo se difundirá con el cañón de un arma, y tienen suficiente experiencia en los muchos horrores de la galaxia para saber que deben luchar con uñas y dientes por ella.',
            'squadron_id' => 5,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "5+",
            'w' => 7,
            'base' => '25mm',
        ],
        [
            'name' => "Mystic Agent",
            'image' => 'mythic_agent.jpg',
            //
            'description' => 'Utilizando sus sentidos empíricos para "ver" verdades ocultas y las almas de aquellos a quienes cazan, los Mystics se involucran en las misiones más arcanas. Proporcionan un apoyo vital a su equipo, adivinando el futuro en busca de peligros o creando escudos de energía psíquica.',
            'squadron_id' => 5,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "5+",
            'w' => 7,
            'base' => '25mm',
        ],
        [
            'name' => "Penal Legionnaire Agent",
            'image' => 'penal_legionnaire_agent.jpg',
            //
            'description' => 'Hay pocas fuentes mejores de luchadores prescindibles con habilidades inusuales y necesidad de arrepentimiento que una Legión Penal Imperial. Estos criminales empedernidos son útiles con la espada y no tienen nada que perder: perfectos para el tipo de misiones suicidas que los agentes inquisitoriales deben afrontar al servicio del Emperador.',
            'squadron_id' => 5,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "5+",
            'w' => 7,
            'base' => '25mm',
        ],
        [
            'name' => "Pistolier Agent",
            'image' => 'pistolier_agent.jpg',
            //
            'description' => 'A veces conocidos como Desperados, estos agentes son asesinos expertos que han perfeccionado sus talentos en las entrañas plagadas de crímenes de los mundos colmena. Además del desenvainado rápido, han aprendido el valor de la matanza silenciosa, así como del ostentosamente explosivo.',
            'squadron_id' => 5,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "5+",
            'w' => 7,
            'base' => '25mm',
        ],
        [
            'name' => "Sister of Silence Prosecutor",
            'image' => 'sisiter_of_silence_prosecutor.jpg',
            //
            'description' => 'Protegidos de la malevolencia de las brujas por su rara mutación antipsíquica y protegidos de las armas del enemigo por su servoarmadura finamente diseñada, Prosecutors avanzan resueltos hacia el corazón de la batalla. Sus bólters truenan sin cesar y cada proyectil explosivo acaba con otra vida hereje.',
            'squadron_id' => 5,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "3+",
            'w' => 8,
            'base' => '32mm',
        ],
        [
            'name' => "Sister of Silence Vigilator",
            'image' => 'sister_of_silence_vigilator.jpg',
            //
            'description' => 'La forma más segura de poner fin al maléfico ataque de una bruja es separarle la cabeza del cuerpo. Ésa es la doctrina de los Vigilantes, que recorren el campo de batalla como fantasmas antes de lanzarse de cabeza a la refriega, mientras sus espadas de energía a dos manos entonan una canción de muerte.',
            'squadron_id' => 5,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "3+",
            'w' => 8,
            'base' => '32mm',
        ],
        [
            'name' => "Sister of Silence Witchseeker",
            'image' => 'sisiter_of_silence_witchseeker.jpg',
            //
            'description' => 'Los Witchseeker empuñan lanzallamas santificados mientras cazan. Para cerrar con su presa herética, emplean sus poderes nulos para cerrar el engaño psíquico que hace que las brujas sean tan letales, antes de desatar una conflagración rugiente para inmolar al enemigo.',
            'squadron_id' => 5,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "3+",
            'w' => 8,
            'base' => '32mm',
        ],
        [
            'name' => "Tempestus Scion Comms",
            'image' => 'tempestus_scion_comms.jpg',
            //
            'description' => 'Equipados con poderosas unidades de comunicación, estos Tempestus Scions pueden transmitir órdenes y datos tácticos precisos a sus compañeros de escuadrón de manera rápida y eficiente. Algunos también están entrenados en contrainteligencia e interceptación de señales, lo que permite a sus compañeros agentes superar al enemigo.',
            'squadron_id' => 5,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "4+",
            'w' => 8,
            'base' => '25mm',
        ],
        [
            'name' => "Tempetus Scion Gunner",
            'image' => 'tempetus_scion_gunner.jpg',
            //
            'description' => 'Tempestus Scions tiene acceso a una variedad más amplia de armas especiales que se adaptan idealmente a todo tipo de misiones. Los artilleros están bien entrenados en su uso, ya sea limpiando un búnker con un lanzallamas o derribando a un enjambre de enemigos fuertemente blindados con una pistola de salvas.',
            'squadron_id' => 5,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "4+",
            'w' => 8,
            'base' => '25mm',
        ],
        [
            'name' => "Tempestus Scion Medic",
            'image' => 'tempestus_scion_medic.jpg',
            //
            'description' => 'En misiones muy detrás de las líneas enemigas, los Tempestus Scions pueden sufrir bajas a muchos kilómetros de su base de operaciones. Sus médicos son vitales para proporcionar ayuda vital a los heridos, para que vuelvan a la lucha antes o para mantenerlos con vida el tiempo suficiente para llevarlos a un lugar seguro.',
            'squadron_id' => 5,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "4+",
            'w' => 8,
            'base' => '25mm',
        ],
        [
            'name' => "Tempestus Scion Trooper",
            'image' => 'tempestus_scion_trooper.jpg',
            //
            'description' => 'Soldados de élite y altamente disciplinados, los Tempestus Scion Troopers cumplen las órdenes sin pestañear. Habiendo recibido un entrenamiento despiadado desde su juventud, hay pocas dificultades que no puedan soportar y pocos enemigos que no puedan vencer.',
            'squadron_id' => 5,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "4+",
            'w' => 8,
            'base' => '25mm',
        ],
        #endregion
        #region Kasrkin
        [
            'name' => "Kasrkin Sergeant",
            'image' => 'kasrkin_sergeant.jpg',
            //
            'description' => 'Los sargentos, líderes de los equipos de combate de Kasrkin, son soldados extremadamente hábiles y experimentados que lideran desde el frente. Experimentan las mismas dificultades que quienes los siguen y son figuras de autoridad imperturbables que saben cómo sacar lo mejor de sus tropas.',
            'squadron_id' => 6,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "4+",
            'w' => 9,
            'base' => '28mm',
        ],
        [
            'name' => "Kasrkin Combat Medic",
            'image' => 'kasrkin_combat_medic.jpg',
            //
            'description' => 'Aunque los Kasrkin se enorgullecen de poder seguir luchando, incluso si están heridos, muchos equipos de exterminio incluyen médicos de combate. Estos Kasrkin cuentan con entrenamiento y equipo adicional para tratar a los heridos y devolverlos a la lucha lo antes posible.',
            'squadron_id' => 6,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "4+",
            'w' => 8,
            'base' => '28mm',
        ],
        [
            'name' => "Kasrkin Demo-Trooper",
            'image' => 'kasrkin_demo_trooper.jpg',
            //
            'description' => 'Vestidos con una armadura más pesada y portando una devastadora mina de fusión, estos Kasrkin desempeñan un papel necesario pero increíblemente peligroso. Su trabajo, a menudo bajo fuego enemigo, es colocar, preparar y detonar una mina de fusión, abriéndose paso hasta un búnker blindado o a través de los muros de una fortaleza.',
            'squadron_id' => 6,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "4+",
            'w' => 8,
            'base' => '28mm',
        ],
        [
            'name' => "Kasrkin Gunner",
            'image' => 'kasrkin_gunner.jpg',
            //
            'description' => 'Estos especialistas reciben entrenamiento adicional en el uso de una variedad de armas diferentes, ya sean lanzallamas para quemar a los enemigos desde la cobertura, pistolas de salvas para atravesar a la infantería pesada enemiga o pistolas de fusión para quemar las armaduras más resistentes.',
            'squadron_id' => 6,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "4+",
            'w' => 8,
            'base' => '28mm',
        ],
        [
            'name' => "Kasrkin Recon-Trooper",
            'image' => 'kasrkin_recon_trooper.jpg',
            //
            'description' => 'Con sus avanzados sistemas auspex, estos Kasrkin son los ojos y oídos de sus equipos de matanza. Pueden detectar tropas enemigas y emboscadas desde distancias significativas, y pueden escanear el terreno local y analizar los sonidos ambientales en busca de peligros.',
            'squadron_id' => 6,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "4+",
            'w' => 8,
            'base' => '28mm',
        ],
        [
            'name' => "Kasrkin Sharpshooter",
            'image' => 'kaskrin_sharpshooter.jpg',
            //
            'description' => 'Estos Kasrkin, pacientes y de mirada aguda, son hábiles francotiradores. Con sus rifles de francotirador pueden matar objetivos clave y proporcionar fuego de cobertura para el resto de su equipo de ataque. Gracias a sus capas de camuflaje, los Sharpshooter pueden infiltrarse en zonas en disputa y permanecer ocultos durante períodos prolongados.',
            'squadron_id' => 6,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "4+",
            'w' => 8,
            'base' => '28mm',
        ],
        [
            'name' => "Kasrkin Trooper",
            'image' => 'kasrkin_trooper.jpg',
            //
            'description' => 'Estos soldados, pertenecientes a las bases de los escuadrones de Kasrkin, son profesionales consumados. Muchos han visto acción en las zonas de muerte más duras y han salido victoriosos.',
            'squadron_id' => 6,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "4+",
            'w' => 8,
            'base' => '28mm',
        ],
        [
            'name' => "Kasrkin Vox-Trooper",
            'image' => 'kasrkin_vox_trooper.jpg',
            //
            'description' => 'Estos Kasrkin, que cuentan con sistemas de comunicación avanzados, son el vínculo de su equipo de ataque con el mando superior. Su trabajo es transmitir órdenes e inteligencia entre los oficiales superiores y sus camaradas, todos los cuales usan sus propios enlaces de voz para una comunicación rápida dentro del escuadrón.',
            'squadron_id' => 6,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "4+",
            'w' => 8,
            'base' => '28mm',
        ],
        #endregion
        #region Veteran Guardsmen
        [
            'name' => "Trooper Veteran",
            'image' => 'trooper_veteran.jpg',
            //
            'description' => 'Los veteranos de Astra Militarum tienen una gran experiencia de combate, adquirida tras experimentar duros combates durante meses o incluso años. Armados con rifles láser y bayonetas, se han enfrentado a terribles peligros una y otra vez.',
            'squadron_id' => 6,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 2,
            'df' => 3,
            'sv' => "5+",
            'w' => 7,
            'base' => '25mm',
        ],
        [
            'name' => "Sergeant Veteran",
            'image' => 'sergeant_veteran.jpg',
            //
            'description' => 'Los Sergeant Veterans dirigen escuadrones de veteranos en batalla. Calmados bajo presión y sin verse afectados por los horrores de la guerra, son líderes de combate sólidos que lucharán con uñas y dientes para lograr la victoria y verán a sus camaradas sobrevivir para luchar otro día.',
            'squadron_id' => 6,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "5+",
            'w' => 8,
            'base' => '25mm',
        ],
        [
            'name' => "Sniper Veteran",
            'image' => 'sniper_veteran.jpg',
            //
            'description' => 'Tiradores expertos, con sus habilidades perfeccionadas en las duras condiciones de numerosos campos de batalla, los Sniper Veterans son francotiradores que se especializan en derribar tropas enemigas clave a distancias extremas, todo ello sin ser visto por el enemigo.',
            'squadron_id' => 6,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "5+",
            'w' => 7,
            'base' => '25mm',
        ],
        [
            'name' => "Gunner Veteran",
            'image' => 'gunner_veteran.jpg',
            //
            'description' => 'Con experiencia y habilidades para manejar una gran cantidad de armas especializadas, los Gunner Veterans son llamados ya sea que un Sargento Veterano necesite un nido xenos reducido a nada, un búnker reducido a lodo derretido o para derribar a la infantería enemiga pesada para la que los rifles láser son insuficientes.',
            'squadron_id' => 6,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "5+",
            'w' => 7,
            'base' => '25mm',
        ],
        [
            'name' => "Confidant Veteran",
            'image' => 'confidant_veteran.jpg',
            //
            'description' => 'Incluso los mejores sargentos veteranos necesitan recurrir a consejos tácticos sólidos, y sus confidentes son expertos. Se puede confiar en que son tropas experimentadas y líderes capaces para llevar a cabo las órdenes del sargento en el campo y contribuir a la formulación de un plan de batalla sólido.',
            'squadron_id' => 6,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "5+",
            'w' => 7,
            'base' => '25mm',
        ],
        [
            'name' => "Demolition Veteran",
            'image' => 'demolition_veteran.jpg',
            //
            'description' => 'Ya sea haciendo estallar depósitos de municiones o abriendo defensas, muchos equipos de exterminio necesitan expertos en explosivos. Los Demolition Veterans son esas tropas. Atrevidos por naturaleza, a menudo tienen que ponerse en peligro para plantar sus minas remotas en el punto óptimo para hacer volar a su objetivo en pedazos.',
            'squadron_id' => 6,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "5+",
            'w' => 7,
            'base' => '25mm',
        ],
        [
            'name' => "Zealot Veteran",
            'image' => 'zealot_veteran.jpg',
            //
            'description' => 'Los Zealot Veterans son guerreros profundamente espirituales y a menudo afirman que su supervivencia en los horribles campos de batalla que han experimentado se debe únicamente a la intervención directa del propio Emperador.',
            'squadron_id' => 6,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "5+",
            'w' => 7,
            'base' => '25mm',
        ],
        [
            'name' => "Medic Veteran",
            'image' => 'medic_veteran.jpg',
            //
            'description' => 'Los esfuerzos del Medic Veteran es lo único que separa la vida y la miserable muerte de las tropas de su escuadrón. Equipados con poco más que equipo médico básico, se esfuerzan por mantener con vida a sus camaradas en las condiciones más peligrosas.',
            'squadron_id' => 6,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "5+",
            'w' => 7,
            'base' => '25mm',
        ],
        [
            'name' => "Comms Veteran",
            'image' => 'comms_veteran.jpg',
            //
            'description' => 'Los Comms Veterans son profesionales consumados, acompañan a sus líderes donde sea necesario mientras transportan equipo pesado, todo para recibir y transmitir comunicaciones que son vitales para que sus camaradas y superiores comprendan la inevitable confusión de la batalla.',
            'squadron_id' => 6,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "5+",
            'w' => 7,
            'base' => '25mm',
        ],
        [
            'name' => "Bruiser Veteran",
            'image' => 'bruiser_veteran.jpg',
            //
            'description' => 'Para algunos, la guerra y la lucha simplemente les sientan bien. Los Bruiser Veterans son esas personas. Miran a los ojos las interminables amenazas malévolas de la galaxia con un garrote de trinchera en la mano, listos para matar a golpes cualquier cosa.',
            'squadron_id' => 6,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "5+",
            'w' => 7,
            'base' => '25mm',
        ],
        [
            'name' => "Hardened Veteran",
            'image' => 'hardened_veteran.jpg',
            //
            'description' => 'Algunos veteranos son más resilientes que incluso sus pares. Estas tropas son de acero tanto en cuerpo como en mente, con biónica en lugar de partes del cuerpo perdidas en la batalla. A pesar de las horribles heridas que han sufrido, siguen luchando inmóviles, imperturbables.',
            'squadron_id' => 6,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "5+",
            'w' => 7,
            'base' => '25mm',
        ],
        [
            'name' => "Spotter Veteran",
            'image' => 'spotter_veteran.jpg',
            //
            'description' => 'Para dirigir el fuego pesado que gana la batalla, los observadores avanzados forman parte de los equipos de combate. Estos Spotter Veterans poseen una gran concentración y guían con precisión salvas de fuego de mortero desde líneas seguras incluso cuando se encuentran bajo una inmensa presión. Con esto pueden bloquear los ataques enemigos o inmovilizarlos en sus defensas.',
            'squadron_id' => 6,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "5+",
            'w' => 7,
            'base' => '25mm',
        ],
        #endregion
        #region Phobos Strike Team
        [
            'name' => "Infiltrator Commsman",
            'image' => 'infiltrator_commsman.jpg',
            //
            'description' => 'El Infiltrator Commsman actúa como un nexo estratégico en el campo de batalla, un conducto a través del cual los intercambios de voz y las cargas de inteligencia pasan como un rayo. La presencia de un hermano de batalla así aumenta la versatilidad y rapidez de acción del equipo de ataque.',
            'squadron_id' => 7,
            'm' => "3 2Circles",
            'apl' => 3,
            'ga' => 1,
            'df' => 3,
            'sv' => "3+",
            'w' => 12,
            'base' => '32mm',
        ],
        [
            'name' => "Infiltator Helix Adept",
            'image' => 'infiltrator_helix_adept.jpg',
            //
            'description' => 'Operando como lo hacen, muy detrás de las líneas enemigas sin apoyo, los Phobos Strike Teams requieren el apoyo médico de los Adeptos de Helix para que los hermanos de batalla heridos vuelvan a la lucha y para recuperar la semilla genética de los caídos para el Capítulo.',
            'squadron_id' => 7,
            'm' => "3 2Circles",
            'apl' => 3,
            'ga' => 1,
            'df' => 3,
            'sv' => "3+",
            'w' => 12,
            'base' => '32mm',
        ],
        [
            'name' => "Infiltrator Saboteur",
            'image' => 'infiltator_saboteur.jpg',
            //
            'description' => 'Llevando a la batalla una letal variedad de cargas de fusión, municiones súper krak e incluso botes antiplantas, el Infiltrator Saboteur está bien preparado para manipular cualquier objetivo para su destrucción. Completada esta tarea, retroceden rápidamente antes de desencadenar una explosión como la ira del Emperador.',
            'squadron_id' => 7,
            'm' => "3 2Circles",
            'apl' => 3,
            'ga' => 1,
            'df' => 3,
            'sv' => "3+",
            'w' => 12,
            'base' => '32mm',
        ],
        [
            'name' => "Infiltrator Veteran",
            'image' => 'infiltrator_veteran.jpg',
            //
            'description' => 'Los hermanos de batalla Infiltrator más experimentados acechan a sus enemigos como fantasmas blindados, empuñando armas seleccionadas de las armerías más exclusivas de su Capítulo, cada una mejorada gracias a la cuidadosa atención de maestros artífices. Así armados, pueden actuar como enemigos de cualquier enemigo.',
            'squadron_id' => 7,
            'm' => "3 2Circles",
            'apl' => 3,
            'ga' => 1,
            'df' => 3,
            'sv' => "3+",
            'w' => 12,
            'base' => '32mm',
        ],
        [
            'name' => "Infiltrator VoxBreaker",
            'image' => 'infiltrator_voxbreaker.jpg',
            //
            'description' => 'El Voxbreaker hace la guerra tanto en el ámbito físico como en el de datos espectrales. Su equipo especializado no sólo les permite escanear y aislar las amenazas enemigas, sino que también pueden irrumpir en las comunicaciones del enemigo y saquearlas en busca de inteligencia estratégica.',
            'squadron_id' => 7,
            'm' => "3 2Circles",
            'apl' => 3,
            'ga' => 1,
            'df' => 3,
            'sv' => "3+",
            'w' => 12,
            'base' => '32mm',
        ],
        [
            'name' => "Infiltrator Warrior",
            'image' => 'infiltator_warrior.jpg',
            //
            'description' => 'Los Infiltrados que luchan como parte de los Phobos Strike Teams son rápidos y agresivos en pensamiento y acción, incluso para los estándares de su hermandad guerrera. Pocos enemigos pueden evadir por mucho tiempo sus puntiagudas andanadas o los destrozadores golpes de sus puños blindados.',
            'squadron_id' => 7,
            'm' => "3 2Circles",
            'apl' => 3,
            'ga' => 1,
            'df' => 3,
            'sv' => "3+",
            'w' => 12,
            'base' => '32mm',
        ],
        [
            'name' => "Infiltrator Sergeant",
            'image' => 'infiltator_sergeant.jpg',
            //
            'description' => 'Ejemplar para sus hermanos; líder estratégico y táctico de habilidad excepcional; Enemigo mortal de los enemigos del Emperador: el Infiltrator Sergeant debe ser todas estas cosas, porque es por sus palabras y acciones que el Equipo de Ataque Phobos se mantiene o cae.',
            'squadron_id' => 7,
            'm' => "3 2Circles",
            'apl' => 3,
            'ga' => 1,
            'df' => 3,
            'sv' => "3+",
            'w' => 13,
            'base' => '32mm',
        ],
        [
            'name' => "Incursor Marksman",
            'image' => 'incursor_marksman.jpg',
            //
            'description' => 'Como si la combinación de un Marine Espacial altamente entrenado y una potente marca de carabina bólter no fuera lo suficientemente letal, el Incursor Marksman emplea su auspex clase Adivinador para rastrear precognitivamente dónde estarán sus objetivos y luego realiza disparos mortales en consecuencia.',
            'squadron_id' => 7,
            'm' => "3 2Circles",
            'apl' => 3,
            'ga' => 1,
            'df' => 3,
            'sv' => "3+",
            'w' => 12,
            'base' => '32mm',
        ],
        [
            'name' => "Incursor Minelayer",
            'image' => 'incursor_minelayer.jpg',
            //
            'description' => 'Algunos Incursor llevan minas pesadas y descontroladas a la batalla y las colocan en nexos premeditados de probable movimiento enemigo. Las explosiones electrofantasmáticas de estas armas pueden desterrar los espíritus de las máquinas del equipo enemigo y paralizar las mejoras augméticas.',
            'squadron_id' => 7,
            'm' => "3 2Circles",
            'apl' => 3,
            'ga' => 1,
            'df' => 3,
            'sv' => "3+",
            'w' => 12,
            'base' => '32mm',
        ],
        [
            'name' => "Incursor Warrior",
            'image' => 'incursor_warrior.jpg',
            //
            'description' => 'Los Incursor son potentes hostigadores ofensivos. Utilizan auspex oraculares acoplados a sus carabinas de perno occulus para detectar objetivos enemigos, incluso a través de paredes sólidas. Luego presionan rápidamente las posiciones de sus enemigos antes de entablar sangrientos tiroteos unilaterales con el enemigo superado.',
            'squadron_id' => 7,
            'm' => "3 2Circles",
            'apl' => 3,
            'ga' => 1,
            'df' => 3,
            'sv' => "3+",
            'w' => 12,
            'base' => '32mm',
        ],
        [
            'name' => "Incursor Sergeant",
            'image' => 'incursor_sergeant.jpg',
            //
            'description' => 'Tendiendo estrategias agresivas y dinámicas, los Incursor Sergeants lideran los Phobos Strike Teams en furiosas ofensivas encubiertas que dejan las estructuras de mando y las cadenas logísticas enemigas hechas jirones, listas para el ataque planetario de una fuerza de ataque de Marines Espaciales en toda regla.',
            'squadron_id' => 7,
            'm' => "3 2Circles",
            'apl' => 3,
            'ga' => 1,
            'df' => 3,
            'sv' => "3+",
            'w' => 13,
            'base' => '32mm',
        ],
        [
            'name' => "Reiver Warrior",
            'image' => 'reiver_warrior.jpg',
            //
            'description' => 'Surgiendo de las sombras en medio de aullidos amplificados por voz, los Reivers caen sobre sus horrorizadas víctimas con pistolas retumbando y espadas blandiendo. Mientras sus enemigos se tambalean por las desorientadoras explosiones de sus granadas de choque, los Reivers hacen un trabajo breve y sangriento con sus víctimas.',
            'squadron_id' => 7,
            'm' => "3 2Circles",
            'apl' => 3,
            'ga' => 1,
            'df' => 3,
            'sv' => "3+",
            'w' => 12,
            'base' => '32mm',
        ],
        [
            'name' => "Reiver Sergeant",
            'image' => 'reiver_sergeant.jpg',
            //
            'description' => 'Los Reiver Sergeants son maestros de la guerra psicológica y las tácticas terroristas. Su misión es manejar su Phobos Strike Team como un bisturí, cortando los tenues hilos de la moral enemiga hasta que las fuerzas del enemigo queden reducidas a una maraña rota y sin nervios.',
            'squadron_id' => 7,
            'm' => "3 2Circles",
            'apl' => 3,
            'ga' => 1,
            'df' => 3,
            'sv' => "3+",
            'w' => 13,
            'base' => '32mm',
        ],
        #endregion
        #region Scout Squad
        [
            'name' => "Scout Sergeant",
            'image' => 'scout_sergeant.jpg',
            //
            'description' => 'Veteranos de su Capítulo, estos guerreros altamente experimentados eligen entrenar a la próxima generación de hermanos de batalla. Predican con el ejemplo y se imponen el respeto de sus pupilos con su valentía y perspicacia táctica.',
            'squadron_id' => 8,
            'm' => "3 2Circles",
            'apl' => 3,
            'ga' => 1,
            'df' => 3,
            'sv' => "4+",
            'w' => 11,
            'base' => '28mm',
        ],
        [
            'name' => "Scout Heavy Gunner",
            'image' => 'scout_heavy_gunner.jpg',
            //
            'description' => 'Estos agentes son guerreros muy capaces que utilizan armas pesadas, desde lanzadores de misiles hasta bólters pesados, para atacar y destruir objetivos enemigos poderosos.',
            'squadron_id' => 8,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "4+",
            'w' => 10,
            'base' => '28mm',
        ],
        [
            'name' => "Scout Hunter",
            'image' => 'scout_hunter.jpg',
            //
            'description' => 'Armados con lanzadores de garfios, los Hunters pueden atravesar rápidamente terrenos peligrosos y negociar terrenos desafiantes para circunnavegar puntos fuertes enemigos, preparar emboscadas o evadir a sus perseguidores.',
            'squadron_id' => 8,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "4+",
            'w' => 10,
            'base' => '28mm',
        ],
        [
            'name' => "Scout Sniper",
            'image' => 'scout_sniper.jpg',
            //
            'description' => 'Los Snipers se destacan en el cumplimiento de los elementos fundamentales de asesinato y reconocimiento en las misiones del Escuadrón Scout. Observan cuidadosamente los movimientos del enemigo desde posiciones ocultas que mantienen durante días, esperando el momento preciso para disparar.',
            'squadron_id' => 8,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "4+",
            'w' => 10,
            'base' => '28mm',
        ],
        [
            'name' => "Scout Tracker",
            'image' => 'scout_tracker.jpg',
            //
            'description' => 'Los Trackers llevan auspex muy potentes: escáneres capaces de analizar el campo de batalla. Gracias a la información que proporcionan estos dispositivos, los escuadrones de exploradores pueden identificar objetivos o planificar rápidamente emboscadas mortales.',
            'squadron_id' => 8,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "4+",
            'w' => 10,
            'base' => '28mm',
        ],
        [
            'name' => "Scout Warrior",
            'image' => 'scout_warrior.jpg',
            //
            'description' => 'Estos agentes son luchadores expertos, comprometidos con su escuadrón y decididos a ascender al estatus de hermano de batalla. No importa lo que la misión les exija, lucharán furiosamente para derrotar al enemigo y demostrar su valía.',
            'squadron_id' => 8,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "4+",
            'w' => 10,
            'base' => '28mm',
        ],
        #endregion
        #region Gellerpox Infected
        #endregion
        #region Legionaries
        #endregion
        #region Blooded
        #endregion
        #region Fellgor Ravagers
        #endregion
        #region Corsair Voidscarred
        #endregion
        #region Blades of Khaine
        #endregion
        #region Hand of the Archon
        #endregion
        #region Farstalker Kindband
        #endregion
        #region Hearthkyn Savagers
        #endregion
        #region Hierotek Circle
        #endregion
        #region Kommandos
        #endregion
        #region Pathfinders
        #endregion
        [
            'name' => "",
            'image' => '',
            //
            'description' => '',
            'squadron_id' => 1,
            'm' => "3 2Circles",
            'apl' => 2,
            'ga' => 1,
            'df' => 3,
            'sv' => "4+",
            'w' => 1,
            'base' => '25mm',
        ],
    ];
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
    }
}
