<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Weapon;

class WeaponSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */

     private $weapons=[
        [
            'name'=>'Autogun',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'2/3',
            'type'=>'ranged',
        ],
        [
            'name'=>'Autopistol',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'2/3',
            'type'=>'ranged',
        ],
        [
            'name'=>'Gun butt',
            'a'=>'3',
            'bs-ws'=>'4+',
            'd'=>'2/3',
            'type'=>'melee',
        ],
        [
            'name'=>'Novitiate blade',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'4/5',
            'type'=>'melee',
        ],
        [
            'name'=>'Bolt pistol',
            'a'=>'4',
            'bs-ws'=>'2+',
            'd'=>'3/4',
            'type'=>'ranged',
        ],
        [
            'name'=>'Bolt gun',
            'a'=>'4',
            'bs-ws'=>'2+',
            'd'=>'3/4',
            'type'=>'ranged',
        ],
        [
            'name'=>'Plasma pistol standard',
            'a'=>'4',
            'bs-ws'=>'2+',
            'd'=>'5/6',
            'type'=>'ranged',
        ],
        [
            'name'=>'Plasma pistol supercharge',
            'a'=>'4',
            'bs-ws'=>'2+',
            'd'=>'5/6',
            'type'=>'ranged',
        ],
        [
            'name'=>'Power weapon',
            'a'=>'4',
            'bs-ws'=>'2+',
            'd'=>'4/6',
            'type'=>'melee',
        ],
        [
            'name'=>'Penitent eviscerator',
            'a'=>'4',
            'bs-ws'=>'4+',
            'd'=>'5/6',
            'type'=>'melee',
        ],
        [
            'name'=>'Ministorum flamer',
            'a'=>'5',
            'bs-ws'=>'2+',
            'd'=>'2/3',
            'type'=>'ranged',
        ],
        [
            'name'=>'Neural whips',
            'a'=>'5',
            'bs-ws'=>'3+',
            'd'=>'2/3',
            'type'=>'ranged',
        ],
        [
            'name'=>'Neural whips',
            'a'=>'5',
            'bs-ws'=>'3+',
            'd'=>'2/3',
            'type'=>'melee',
        ],
        [
            'name'=>'Surgical saw',
            'a'=>'4',
            'bs-ws'=>'4+',
            'd'=>'2/3',
            'type'=>'melee',
        ],
        [
            'name'=>'Mace of the Righteous',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'5/5',
            'type'=>'melee',
        ],
        [
            'name'=>'Dialogus stave',
            'a'=>'3',
            'bs-ws'=>'4+',
            'd'=>'3/3',
            'type'=>'melee',
        ],
        [
            'name'=>'Duelling blades',
            'a'=>'4',
            'bs-ws'=>'2+',
            'd'=>'3/4',
            'type'=>'melee',
        ],
        [
            'name'=>'Condemnor stakethrower',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'2/3',
            'type'=>'ranged',
        ],
        [
            'name'=>'Null rod',
            'a'=>'3',
            'bs-ws'=>'3+',
            'd'=>'3/3',
            'type'=>'melee',
        ],
        [
            'name'=>'Digital laser',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'0/0',
            'type'=>'ranged',
        ],
        [
            'name'=>'Heirloom relic pistol',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'4/5',
            'type'=>'ranged',
        ],
        [
            'name'=>'Monomolecular cane-rapier',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'3/6',
            'type'=>'melee',
        ],
        [
            'name'=>'Vicious bite',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'3/4',
            'type'=>'melee',
        ],
        [
            'name'=>'Dartmask',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'1/1',
            'type'=>'ranged',
        ],
        [
            'name'=>'Power weapon',
            'a'=>'5',
            'bs-ws'=>'2+',
            'd'=>'4/6',
            'type'=>'melee',
        ],
        [
            'name'=>'Voltaic pistol',
            'a'=>'4',
            'bs-ws'=>'4+',
            'd'=>'4/4',
            'type'=>'ranged',
        ],
        [
            'name'=>'Laspistol',
            'a'=>'4',
            'bs-ws'=>'4+',
            'd'=>'2/3',
            'type'=>'ranged',
        ],
        [
            'name'=>'Scalpel claw',
            'a'=>'3',
            'bs-ws'=>'4+',
            'd'=>'3/4',
            'type'=>'melee',
        ],
        [
            'name'=>'Artificer shotgun close range',
            'a'=>'4',
            'bs-ws'=>'2+',
            'd'=>'4/4',
            'type'=>'ranged',
        ],
        [
            'name'=>'Artificer shotgun long range',
            'a'=>'4',
            'bs-ws'=>'4+',
            'd'=>'2/3',
            'type'=>'ranged',
        ],
        [
            'name'=>'Lasgun',
            'a'=>'4',
            'bs-ws'=>'4+',
            'd'=>'2/3',
            'type'=>'ranged',
        ],
        [
            'name'=>'Rotor cannon',
            'a'=>'6',
            'bs-ws'=>'4+',
            'd'=>'3/4',
            'type'=>'ranged',
        ],
        [
            'name'=>'Combat shotgun close range',
            'a'=>'4',
            'bs-ws'=>'2+',
            'd'=>'4/4',
            'type'=>'ranged',
        ],
        [
            'name'=>'Combat shotgun long range',
            'a'=>'4',
            'bs-ws'=>'4+',
            'd'=>'2/2',
            'type'=>'ranged',
        ],
        [
            'name'=>'Repression baton',
            'a'=>'3',
            'bs-ws'=>'4+',
            'd'=>'2/2',
            'type'=>'melee',
        ],
        [
            'name'=>'Dominator maul & assault shield',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'4/4',
            'type'=>'melee',
        ],
        [
            'name'=>'Excruciator maul',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'4/4',
            'type'=>'melee',
        ],
        [
            'name'=>'Granade launcher',
            'a'=>'4',
            'bs-ws'=>'4+',
            'd'=>'4/6',
            'type'=>'ranged',
        ],
        [
            'name'=>'Heavy stubber',
            'a'=>'5',
            'bs-ws'=>'4+',
            'd'=>'3/4',
            'type'=>'ranged',
        ],
        [
            'name'=>'Webber',
            'a'=>'5',
            'bs-ws'=>'3+',
            'd'=>'2/2',
            'type'=>'ranged',
        ],
        [
            'name'=>'Mechanical bite',
            'a'=>'4',
            'bs-ws'=>'4+',
            'd'=>'3/5',
            'type'=>'melee',
        ],
        [
            'name'=>'Executioner shotgun',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'4/1',
            'type'=>'ranged',
        ],
        [
            'name'=>'Scoped shotpistol',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'3/1',
            'type'=>'ranged',
        ],
        [
            'name'=>'Shock maul & assault shield',
            'a'=>'4',
            'bs-ws'=>'4+',
            'd'=>'4/4',
            'type'=>'melee',
        ],
        [
            'name'=>'Bolt pistol',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'3/4',
            'type'=>'ranged',
        ],
        [
            'name'=>'Heirloom autopistol',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'2/3',
            'type'=>'ranged',
        ],
        [
            'name'=>'Navis shotgun close range',
            'a'=>'4',
            'bs-ws'=>'2+',
            'd'=>'3/3',
            'type'=>'ranged',
        ],
        [
            'name'=>'Navis shotgun long range',
            'a'=>'4',
            'bs-ws'=>'4+',
            'd'=>'1/2',
            'type'=>'',
        ],
        [
            'name'=>'Chainsword',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'4/5',
            'type'=>'melee',
        ],
        [
            'name'=>'Navis hatchet',
            'a'=>'3',
            'bs-ws'=>'3+',
            'd'=>'3/4',
            'type'=>'melee',
        ],
        [
            'name'=>'Power weapon',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'4/6',
            'type'=>'melee',
        ],
        [
            'name'=>'Navis heavy shotgun close range',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'3/3',
            'type'=>'ranged',
        ],
        [
            'name'=>'Navis heavy shotgun long range',
            'a'=>'4',
            'bs-ws'=>'5+',
            'd'=>'1/2',
            'type'=>'ranged',
        ],
        [
            'name'=>'Shield bash',
            'a'=>'3',
            'bs-ws'=>'4+',
            'd'=>'1/1',
            'type'=>'melee',
        ],
        [
            'name'=>'Demolition charge',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'4/6',
            'type'=>'ranged',
        ],
        [
            'name'=>'Navis las-volley',
            'a'=>'6',
            'bs-ws'=>'4+',
            'd'=>'3/4',
            'type'=>'ranged',
        ],
        [
            'name'=>'Meltagun',
            'a'=>'4',
            'bs-ws'=>'4+',
            'd'=>'6/3',
            'type'=>'ranged',
        ],
        [
            'name'=>'Plasma gun standard',
            'a'=>'4',
            'bs-ws'=>'4+',
            'd'=>'5/6',
            'type'=>'ranged',
        ],
        [
            'name'=>'Plasma gun supercharge',
            'a'=>'4',
            'bs-ws'=>'4+',
            'd'=>'5/6',
            'type'=>'ranged',
        ],
        [
            'name'=>'Chainfist',
            'a'=>'4',
            'bs-ws'=>'4+',
            'd'=>'5/6',
            'type'=>'melee',
        ],
        [
            'name'=>'Gheistskull detonator',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'2/3',
            'type'=>'ranged',
        ],
        [
            'name'=>'Extended stock autopistol close range',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'2/3',
            'type'=>'ranged',
        ],
        [
            'name'=>'Extended stock autopistol long range',
            'a'=>'4',
            'bs-ws'=>'4+',
            'd'=>'2/3',
            'type'=>'ranged',
        ],
        [
            'name'=>'Fists',
            'a'=>'3',
            'bs-ws'=>'4+',
            'd'=>'2/3',
            'type'=>'melee',
        ],
        [
            'name'=>'Mechanical appendages',
            'a'=>'3',
            'bs-ws'=>'5+',
            'd'=>'1/2',
            'type'=>'melee',
        ],
        [
            'name'=>'Eviscerator',
            'a'=>'4',
            'bs-ws'=>'4+',
            'd'=>'5/6',
            'type'=>'melee',
        ],
        [
            'name'=>'Knife',
            'a'=>'1',
            'bs-ws'=>'2+',
            'd'=>'5/7',
            'type'=>'melee',
        ],
        [
            'name'=>'Polearm',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'4/5',
            'type'=>'melee',
        ],
        [
            'name'=>'Paired blades',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'3/5',
            'type'=>'melee',
        ],
        [
            'name'=>'Heavy bolter',
            'a'=>'5',
            'bs-ws'=>'4+',
            'd'=>'4/5',
            'type'=>'ranged',
        ],
        [
            'name'=>'Multi-melta',
            'a'=>'4',
            'bs-ws'=>'4+',
            'd'=>'6/3',
            'type'=>'ranged',
        ],
        [
            'name'=>'Plasma cannon standard',
            'a'=>'4',
            'bs-ws'=>'4+',
            'd'=>'5/6',
            'type'=>'ranged',
        ],
        [
            'name'=>'Plasma cannon supercharge',
            'a'=>'4',
            'bs-ws'=>'4+',
            'd'=>'5/6',
            'type'=>'ranged',
        ],
        [
            'name'=>'Servo claw',
            'a'=>'3',
            'bs-ws'=>'4+',
            'd'=>'4/5',
            'type'=>'melee',
        ],
        [
            'name'=>'Shotgun',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'3/3',
            'type'=>'ranged',
        ],
        [
            'name'=>'Hand flamer',
            'a'=>'5',
            'bs-ws'=>'2+',
            'd'=>'2/2',
            'type'=>'ranged',
        ],
        [
            'name'=>'Chainsword',
            'a'=>'4',
            'bs-ws'=>'4+',
            'd'=>'4/5',
            'type'=>'melee',
        ],
        [
            'name'=>'Scoped plasma pistol scoped',
            'a'=>'4',
            'bs-ws'=>'4+',
            'd'=>'4/5',
            'type'=>'ranged',
        ],
        [
            'name'=>'Scoped plasma pistol standard',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'5/6',
            'type'=>'ranged',
        ],
        [
            'name'=>'Scoped plasma pistol supercharge',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'5/6',
            'type'=>'ranged',
        ],
        [
            'name'=>'Suppressed autopistol',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'2/3',
            'type'=>'ranged',
        ],
        [
            'name'=>'Bolt gun',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'3/4',
            'type'=>'ranged',
        ],
        [
            'name'=>'Executioner greatblade',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'4/6',
            'type'=>'melee',
        ],
        [
            'name'=>'Flamer',
            'a'=>'5',
            'bs-ws'=>'2+',
            'd'=>'2/2',
            'type'=>'ranged',
        ],
        [
            'name'=>'Hot-shot lasgun',
            'a'=>'4',
            'bs-ws'=>'4+',
            'd'=>'3/4',
            'type'=>'ranged',
        ],
        [
            'name'=>'Grenade launcher frag',
            'a'=>'4',
            'bs-ws'=>'4+',
            'd'=>'2/4',
            'type'=>'ranged',
        ],
        [
            'name'=>'Grenade launcher krak',
            'a'=>'4',
            'bs-ws'=>'4+',
            'd'=>'4/5',
            'type'=>'ranged',
        ],
        [
            'name'=>'Hot-shot volley gun',
            'a'=>'5',
            'bs-ws'=>'4+',
            'd'=>'3/4',
            'type'=>'ranged',
        ],
        [
            'name'=>'Hot-shot laspistol',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'3/4',
            'type'=>'ranged',
        ],
        [
            'name'=>'Melta mine',
            'a'=>'4',
            'bs-ws'=>'2+',
            'd'=>'4/2',
            'type'=>'ranged',
        ],
        [
            'name'=>'Hot-shot marksman rifle sharpshot',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'3/4',
            'type'=>'ranged',
        ],
        [
            'name'=>'Hot-shot marksman rifle snipe',
            'a'=>'4',
            'bs-ws'=>'2+',
            'd'=>'3/3',
            'type'=>'ranged',
        ],
        [
            'name'=>'Bayonet',
            'a'=>'3',
            'bs-ws'=>'4+',
            'd'=>'2/3',
            'type'=>'melee',
        ],
        [
            'name'=>'Long-las',
            'a'=>'4',
            'bs-ws'=>'2+',
            'd'=>'3/3',
            'type'=>'ranged',
        ],
        [
            'name'=>'Las pistol',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'2/3',
            'type'=>'ranged',
        ],
        [
            'name'=>'Boltgun',
            'a'=>'4',
            'bs-ws'=>'4+',
            'd'=>'3/4',
            'type'=>'ranged',
        ],
        [
            'name'=>'Trench club',
            'a'=>'3',
            'bs-ws'=>'3+',
            'd'=>'3/3',
            'type'=>'melee',
        ],
        [
            'name'=>'Bionic arm',
            'a'=>'3',
            'bs-ws'=>'4+',
            'd'=>'4/5',
            'type'=>'melee',
        ],
        [
            'name'=>'Mortar barrage',
            'a'=>'5',
            'bs-ws'=>'4+',
            'd'=>'2/3',
            'type'=>'ranged',
        ],
        [
            'name'=>'Marksman bolt carbine',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'3/4',
            'type'=>'ranged',
        ],
        [
            'name'=>'Remote explosives',
            'a'=>'4',
            'bs-ws'=>'2+',
            'd'=>'5/6',
            'type'=>'ranged',
        ],
        [
            'name'=>'Custom bolt carbine',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'3/4',
            'type'=>'ranged',
        ],
        [
            'name'=>'Combat blade',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'3/5',
            'type'=>'melee',
        ],
        [
            'name'=>'Stalker marksman bolt carbine',
            'a'=>'4',
            'bs-ws'=>'2+',
            'd'=>'3/4',
            'type'=>'ranged',
        ],
        [
            'name'=>'Haywire mine',
            'a'=>'4',
            'bs-ws'=>'2+',
            'd'=>'2/4',
            'type'=>'ranged',
        ],
        [
            'name'=>'Occulus bolt carbine',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'3/4',
            'type'=>'ranged',
        ],
        [
            'name'=>'Special issue bolt pistol',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'3/4',
            'type'=>'ranged',
        ],
        [
            'name'=>'Astartes shotgun',
            'a'=>'4',
            'bs-ws'=>'2+',
            'd'=>'4/4',
            'type'=>'ranged',
        ],
        [
            'name'=>'Missile launcher frag',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'3/5',
            'type'=>'ranged',
        ],
        [
            'name'=>'Missile launcher krak',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'5/7',
            'type'=>'ranged',
        ],
        [
            'name'=>'Snipe rifle',
            'a'=>'4',
            'bs-ws'=>'2+',
            'd'=>'3/3',
            'type'=>'ranged',
        ],
        [
            'name'=>'Bloodsucking proboscis',
            'a'=>'2',
            'bs-ws'=>'4+',
            'd'=>'2/3',
            'type'=>'ranged',
        ],
        [
            'name'=>'Swarm',
            'a'=>'5',
            'bs-ws'=>'6+',
            'd'=>'0/0',
            'type'=>'ranged',
        ],
        [
            'name'=>'Sting',
            'a'=>'5',
            'bs-ws'=>'5+',
            'd'=>'1/2',
            'type'=>'melee',
        ],
        [
            'name'=>'Acid spit',
            'a'=>'4',
            'bs-ws'=>'4+',
            'd'=>'2/2',
            'type'=>'ranged',
        ],
        [
            'name'=>'Fanged maw',
            'a'=>'2',
            'bs-ws'=>'4+',
            'd'=>'1/3',
            'type'=>'melee',
        ],
        [
            'name'=>'Pyregut',
            'a'=>'6',
            'bs-ws'=>'2+',
            'd'=>'3/3',
            'type'=>'ranged',
        ],
        [
            'name'=>'Fleshmelded weapons',
            'a'=>'5',
            'bs-ws'=>'3+',
            'd'=>'4/5',
            'type'=>'melee',
        ],
        [
            'name'=>'Mutant tentacles',
            'a'=>'6',
            'bs-ws'=>'4+',
            'd'=>'3/4',
            'type'=>'ranged',
        ],
        [
            'name'=>'Mutant claw & tentacles grasp and slash',
            'a'=>'6',
            'bs-ws'=>'4+',
            'd'=>'3/4',
            'type'=>'melee',
        ],
        [
            'name'=>'Mutant claw & tentacles writhing swipe',
            'a'=>'3',
            'bs-ws'=>'4+',
            'd'=>'e/4',
            'type'=>'melee',
        ],
        [
            'name'=>'Mutant fist & cleaver bash and slash',
            'a'=>'5',
            'bs-ws'=>'4+',
            'd'=>'5/6',
            'type'=>'melee',
        ],
        [
            'name'=>'Mutant fist & cleaver lopping blow',
            'a'=>'1',
            'bs-ws'=>'3+',
            'd'=>'8/9',
            'type'=>'melee',
        ],
        [
            'name'=>'Mutant claw',
            'a'=>'4',
            'bs-ws'=>'4+',
            'd'=>'6/7',
            'type'=>'melee',
        ],
        [
            'name'=>'Frag grenade',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'2/3',
            'type'=>'ranged',
        ],
        [
            'name'=>'Heavy axe',
            'a'=>'3',
            'bs-ws'=>'4+',
            'd'=>'4/5',
            'type'=>'melee',
        ],
        [
            'name'=>'Improvised weapon & mutant limb',
            'a'=>'4',
            'bs-ws'=>'4+',
            'd'=>'2/3',
            'type'=>'melee',
        ],
        [
            'name'=>'Diseased effluence',
            'a'=>'4',
            'bs-ws'=>'4+',
            'd'=>'1/2',
            'type'=>'ranged',
        ],
        [
            'name'=>'Diseased nippers',
            'a'=>'3',
            'bs-ws'=>'4+',
            'd'=>'1/2',
            'type'=>'melee',
        ],
        [
            'name'=>'Reaper chaincannon',
            'a'=>'6',
            'bs-ws'=>'3+',
            'd'=>'3/5',
            'type'=>'ranged',
        ],
        [
            'name'=>'Daemonic claw',
            'a'=>'5',
            'bs-ws'=>'3+',
            'd'=>'4/5',
            'type'=>'melee',
        ],
        [
            'name'=>'Double-handed chain axe',
            'a'=>'4',
            'bs-ws'=>'4+',
            'd'=>'5/7',
            'type'=>'melee',
        ],
        [
            'name'=>'Flensing blades',
            'a'=>'5',
            'bs-ws'=>'3+',
            'd'=>'3/5',
            'type'=>'melee',
        ],
        [
            'name'=>'Chainsword',
            'a'=>'5',
            'bs-ws'=>'3+',
            'd'=>'4/5',
            'type'=>'melee',
        ],
        [
            'name'=>'Tainted bolt pistol',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'3/4',
            'type'=>'ranged',
        ],
        [
            'name'=>'Fell dagger',
            'a'=>'5',
            'bs-ws'=>'3+',
            'd'=>'3/4',
            'type'=>'melee',
        ],
        [
            'name'=>'Daemon blade',
            'a'=>'5',
            'bs-ws'=>'2+',
            'd'=>'4/7',
            'type'=>'melee',
        ],
        [
            'name'=>'Power maul',
            'a'=>'5',
            'bs-ws'=>'2+',
            'd'=>'4/6',
            'type'=>'melee',
        ],
        [
            'name'=>'Tainted chainsword',
            'a'=>'5',
            'bs-ws'=>'2+',
            'd'=>'4/5',
            'type'=>'melee',
        ],
        [
            'name'=>'Diabolyk bomb',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'3/3',
            'type'=>'ranged',
        ],
        [
            'name'=>'Power weapon and cleaver',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'4/6',
            'type'=>'melee',
        ],
        [
            'name'=>'Stim needle',
            'a'=>'3',
            'bs-ws'=>'5+',
            'd'=>'1/4',
            'type'=>'melee',
        ],
        [
            'name'=>'Power fist',
            'a'=>'4',
            'bs-ws'=>'4+',
            'd'=>'5/7',
            'type'=>'melee',
        ],
        [
            'name'=>'Power maul and mutant claw',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'5/6',
            'type'=>'melee',
        ],
        [
            'name'=>"Sharpshooter's long-las",
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'3/3',
            'type'=>'ranged',
        ],
        [
            'name'=>'Heavy club',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'4/4',
            'type'=>'melee',
        ],
        [
            'name'=>'Bayonet and shield',
            'a'=>'3',
            'bs-ws'=>'3+',
            'd'=>'2/3',
            'type'=>'melee',
        ],
        [
            'name'=>'Improvised blade',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'2/3',
            'type'=>'melee',
        ],
        [
            'name'=>'Corrupted pistol',
            'a'=>'4',
            'bs-ws'=>'4+',
            'd'=>'3/5',
            'type'=>'ranged',
        ],
        [
            'name'=>'Bludgeon',
            'a'=>'4',
            'bs-ws'=>'2+',
            'd'=>'4/4',
            'type'=>'melee',
        ],
        [
            'name'=>'Corrupted chainsword',
            'a'=>'4',
            'bs-ws'=>'2+',
            'd'=>'4/5',
            'type'=>'melee',
        ],
        [
            'name'=>'Triple cleavers offensive',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'4/5',
            'type'=>'melee',
        ],
        [
            'name'=>'Triple cleavers defensive',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'4/5',
            'type'=>'melee',
        ],
        [
            'name'=>'Bionic fist',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'4/5',
            'type'=>'melee',
        ],
        [
            'name'=>'Skullcleaver',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'4/5',
            'type'=>'melee',
        ],
        [
            'name'=>'Crackthorn whip',
            'a'=>'4',
            'bs-ws'=>'2+',
            'd'=>'2/3',
            'type'=>'ranged',
        ],
        [
            'name'=>'Crackthorn whip',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'`2/3',
            'type'=>'melee',
        ],
        [
            'name'=>'Vicious claws',
            'a'=>'4',
            'bs-ws'=>'4+',
            'd'=>'4/6',
            'type'=>'melee',
        ],
        [
            'name'=>'Blaystave',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'3/5',
            'type'=>'melee',
        ],
        [
            'name'=>'Cleaver',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'4/5',
            'type'=>'melee',
        ],
        
        [
            'name'=>'Mancrusher',
            'a'=>'4',
            'bs-ws'=>'4+',
            'd'=>'5/5',
            'type'=>'melee',
        ],
        [
            'name'=>'Shuriken pistol',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'3/4',
            'type'=>'ranged',
        ],
        [
            'name'=>'Shuriken rifle',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'3/4',
            'type'=>'ranged',
        ],
        [
            'name'=>'Blaster',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'3/4',
            'type'=>'ranged',
        ],
        [
            'name'=>'Shredder',
            'a'=>'5',
            'bs-ws'=>'3+',
            'd'=>'3/4',
            'type'=>'ranged',
        ],
        [
            'name'=>'Shuriken cannon',
            'a'=>'5',
            'bs-ws'=>'3+',
            'd'=>'4/5',
            'type'=>'ranged',
        ],
        [
            'name'=>'Wraithcannon',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'6/3',
            'type'=>'ranged',
        ],
        [
            'name'=>'Fusion pistol',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'5/3',
            'type'=>'ranged',
        ],
        [
            'name'=>'Throwing blades',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'2/4',
            'type'=>'ranged',
        ],
        [
            'name'=>'Hekatarii blades',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'3/5',
            'type'=>'melee',
        ],
        [
            'name'=>'Dual power weapons',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'4/6',
            'type'=>'melee',
        ],
        [
            'name'=>'Ranger long rifle',
            'a'=>'4',
            'bs-ws'=>'2+',
            'd'=>'3/3',
            'type'=>'ranged',
        ],
        [
            'name'=>'Witch staff',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'3/5',
            'type'=>'melee',
        ],
        [
            'name'=>'Neuro disruptor',
            'a'=>'4',
            'bs-ws'=>'2+',
            'd'=>'4/5',
            'type'=>'ranged',
        ],
        [
            'name'=>'Shuriken catapult',
            'a'=>'4',
            'bs-ws'=>'2+',
            'd'=>'3/4',
            'type'=>'ranged',
        ],
        [
            'name'=>'Twin shuriken catapult',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'3/3',
            'type'=>'ranged',
        ],
        [
            'name'=>'Diresword',
            'a'=>'5',
            'bs-ws'=>'2+',
            'd'=>'4/5',
            'type'=>'melee',
        ],
        [
            'name'=>'Triskele',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'2/3',
            'type'=>'ranged',
        ],
        [
            'name'=>'Executioner',
            'a'=>'5',
            'bs-ws'=>'2+',
            'd'=>'3/7',
            'type'=>'melee',
        ],
        [
            'name'=>'Mirrorswords',
            'a'=>'5',
            'bs-ws'=>'2+',
            'd'=>'4/6',
            'type'=>'melee',
        ],
        [
            'name'=>'Triskele',
            'a'=>'6',
            'bs-ws'=>'2+',
            'd'=>'3/4',
            'type'=>'melee',
        ],
        [
            'name'=>'Twin shuriken pistols',
            'a'=>'4',
            'bs-ws'=>'4+',
            'd'=>'3/4',
            'type'=>'ranged',
        ],
        [
            'name'=>'Biting blade',
            'a'=>'5',
            'bs-ws'=>'2+',
            'd'=>'5/6',
            'type'=>'melee',
        ],
        [
            'name'=>'Twin chainswords',
            'a'=>'5',
            'bs-ws'=>'2+',
            'd'=>'4/5',
            'type'=>'melee',
        ],
        [
            'name'=>"Scorpion's claw and chainsword",
            'a'=>'5',
            'bs-ws'=>'2+',
            'd'=>'4/6',
            'type'=>'melee',
        ],
        [
            'name'=>'Blast pistol',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'4/5',
            'type'=>'ranged',
        ],
        [
            'name'=>'Splinter pistol',
            'a'=>'4',
            'bs-ws'=>'2+',
            'd'=>'2/4',
            'type'=>'ranged',
        ],
        [
            'name'=>'Splinter rifle',
            'a'=>'4',
            'bs-ws'=>'2+',
            'd'=>'2/4',
            'type'=>'ranged',
        ],
        [
            'name'=>'Agoniser',
            'a'=>'4',
            'bs-ws'=>'2+',
            'd'=>'3/6',
            'type'=>'melee',
        ],
        [
            'name'=>'Array of blades',
            'a'=>'3',
            'bs-ws'=>'2+',
            'd'=>'3/4',
            'type'=>'melee',
        ],
        [
            'name'=>'Venom blade',
            'a'=>'4',
            'bs-ws'=>'2+',
            'd'=>'4/4',
            'type'=>'melee',
        ],
        [
            'name'=>'Razorflails',
            'a'=>'4',
            'bs-ws'=>'2+',
            'd'=>'4/5',
            'type'=>'melee',
        ],
        [
            'name'=>'Stinger pistol',
            'a'=>'5',
            'bs-ws'=>'*',
            'd'=>'0/0',
            'type'=>'ranged',
        ],
        [
            'name'=>'Stimm-needler',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'0/0',
            'type'=>'ranged',
        ],
        [
            'name'=>'Pain sculptors',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'3/5',
            'type'=>'melee',
        ],
        [
            'name'=>'Dark lance',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'6/7',
            'type'=>'ranged',
        ],
        [
            'name'=>'Razorwing',
            'a'=>'5',
            'bs-ws'=>'4+',
            'd'=>'1/2',
            'type'=>'ranged',
        ],
        [
            'name'=>'Shardcarbine',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'2/2',
            'type'=>'ranged',
        ],
        [
            'name'=>'Kroot rifle',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'3/4',
            'type'=>'ranged',
        ],
        [
            'name'=>'Pulse carbine',
            'a'=>'4',
            'bs-ws'=>'4+',
            'd'=>'4/4',
            'type'=>'ranged',
        ],
        [
            'name'=>'Pulse rifle',
            'a'=>'4',
            'bs-ws'=>'4+',
            'd'=>'4/5',
            'type'=>'ranged',
        ],
        [
            'name'=>'Blade',
            'a'=>'4',
            'bs-ws'=>'2+',
            'd'=>'3/4',
            'type'=>'melee',
        ],
        [
            'name'=>'Accelerator bow fused arrow',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'4/5',
            'type'=>'ranged',
        ],
        [
            'name'=>'Accelerator bow glide arrow',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'3/4',
            'type'=>'ranged',
        ],
        [
            'name'=>'Accelerator bow voltaic arrow',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'3/2',
            'type'=>'ranged',
        ],
        [
            'name'=>"Cut-skin's blades",
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'3/4',
            'type'=>'melee',
        ],
        [
            'name'=>'Dvorgite skinner',
            'a'=>'6',
            'bs-ws'=>'2+',
            'd'=>'2/3',
            'type'=>'ranged',
        ],
        [
            'name'=>'Londaxi tribalets',
            'a'=>'5',
            'bs-ws'=>'4+',
            'd'=>'4/4',
            'type'=>'ranged',
        ],
        [
            'name'=>'Ripping fangs',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'3/4',
            'type'=>'melee',
        ],
        [
            'name'=>'Kroot hunting rifle',
            'a'=>'4',
            'bs-ws'=>'2+',
            'd'=>'3/3',
            'type'=>'ranged',
        ],
        [
            'name'=>'Dual kroot pistols',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'3/4',
            'type'=>'ranged',
        ],
        [
            'name'=>'Kroot scattergun',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'3/3',
            'type'=>'ranged',
        ],
        [
            'name'=>"Stalker's blade",
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'3/3',
            'type'=>'melee',
        ],
        [
            'name'=>'Autoch-pattern bolt pistol',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'3/4',
            'type'=>'ranged',
        ],
        [
            'name'=>'Autoch-pattern bolter',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'3/4',
            'type'=>'ranged',
        ],
        [
            'name'=>'Bolt revolver',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'3/5',
            'type'=>'ranged',
        ],
        [
            'name'=>'Etacarn plasma pistol',
            'a'=>'4',
            'bs-ws'=>'4+',
            'd'=>'3/5',
            'type'=>'ranged',
        ],
        [
            'name'=>'Ion blaster',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'3/4',
            'type'=>'ranged',
        ],
        [
            'name'=>'Ion pistol',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'3/4',
            'type'=>'ranged',
        ],
        [
            'name'=>'Concurssion gauntlet',
            'a'=>'4',
            'bs-ws'=>'4+',
            'd'=>'5/6',
            'type'=>'melee',
        ],
        [
            'name'=>'Plasma axe',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'5/5',
            'type'=>'melee',
        ],
        [
            'name'=>'Plasma sword',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'4/6',
            'type'=>'melee',
        ],
        [
            'name'=>'Concussion knux',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'4/4',
            'type'=>'melee',
        ],
        [
            'name'=>'Plasma knife',
            'a'=>'4',
            'bs-ws'=>'4+',
            'd'=>'3/5',
            'type'=>'melee',
        ],
        [
            'name'=>'C8 HX charge',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'4/6',
            'type'=>'ranged',
        ],
        [
            'name'=>'EtaCarn plasma beamer',
            'a'=>'4',
            'bs-ws'=>'4+',
            'd'=>'4/6',
            'type'=>'ranged',
        ],
        [
            'name'=>'HYLas auto rifle',
            'a'=>'4',
            'bs-ws'=>'4+',
            'd'=>'3/4',
            'type'=>'ranged',
        ],
        [
            'name'=>'HYLas rotary cannon',
            'a'=>'6',
            'bs-ws'=>'4+',
            'd'=>'3/5',
            'type'=>'ranged',
        ],
        [
            'name'=>'L7 missile launcher blast',
            'a'=>'4',
            'bs-ws'=>'4+',
            'd'=>'3/5',
            'type'=>'ranged',
        ],
        [
            'name'=>'L7 missile launcher focused',
            'a'=>'4',
            'bs-ws'=>'4+',
            'd'=>'5/6',
            'type'=>'ranged',
        ],
        [
            'name'=>'Magma rail rifle',
            'a'=>'4',
            'bs-ws'=>'4+',
            'd'=>'5/4',
            'type'=>'ranged',
        ],
        [
            'name'=>'Aeonstave',
            'a'=>'5',
            'bs-ws'=>'3+',
            'd'=>'3/3',
            'type'=>'ranged',
        ],
        [
            'name'=>'Entropic lance',
            'a'=>'3',
            'bs-ws'=>'3+',
            'd'=>'3/3',
            'type'=>'ranged',
        ],
        [
            'name'=>'Aeonstave',
            'a'=>'3',
            'bs-ws'=>'3+',
            'd'=>'3/3',
            'type'=>'melee',
        ],
        [
            'name'=>'Entropic lance',
            'a'=>'3',
            'bs-ws'=>'3+',
            'd'=>'3/6',
            'type'=>'melee',
        ],
        [
            'name'=>'Abyssal lance',
            'a'=>'5',
            'bs-ws'=>'3+',
            'd'=>'2/2',
            'type'=>'ranged',
        ],
        [
            'name'=>'Abyssal lance',
            'a'=>'3',
            'bs-ws'=>'3+',
            'd'=>'2/3',
            'type'=>'melee',
        ],
        [
            'name'=>'Staff of ligth',
            'a'=>'6',
            'bs-ws'=>'3+',
            'd'=>'3/4',
            'type'=>'ranged',
        ],
        [
            'name'=>'Staff of light',
            'a'=>'3',
            'bs-ws'=>'3+',
            'd'=>'3/5',
            'type'=>'melee',
        ],
        [
            'name'=>'Spark',
            'a'=>'4',
            'bs-ws'=>'4+',
            'd'=>'2/3',
            'type'=>'ranged',
        ],
        [
            'name'=>'Claws',
            'a'=>'3',
            'bs-ws'=>'5+',
            'd'=>'1/2',
            'type'=>'melee',
        ],
        [
            'name'=>'Arcane conduit',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'3/4',
            'type'=>'ranged',
        ],
        [
            'name'=>'Arcane conduit',
            'a'=>'3',
            'bs-ws'=>'3+',
            'd'=>'3/5',
            'type'=>'melee',
        ],
        [
            'name'=>'Synaptic disintegrator',
            'a'=>'4',
            'bs-ws'=>'2+',
            'd'=>'4/4',
            'type'=>'ranged',
        ],
        [
            'name'=>'Gauss blaster',
            'a'=>'4',
            'bs-ws'=>'2+',
            'd'=>'4/5',
            'type'=>'ranged',
        ],
        [
            'name'=>'Tesla carbine',
            'a'=>'5',
            'bs-ws'=>'2+',
            'd'=>'3/3',
            'type'=>'ranged',
        ],
        [
            'name'=>'Bayonet',
            'a'=>'4',
            'bs-ws'=>'2+',
            'd'=>'3/4',
            'type'=>'melee',
        ],
        [
            'name'=>'Gauss blaster',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'4/5',
            'type'=>'ranged',
        ],
        [
            'name'=>'Tesla carbine',
            'a'=>'5',
            'bs-ws'=>'3+',
            'd'=>'3/3',
            'type'=>'ranged',
        ],
        [
            'name'=>'Bayonet',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'3/4',
            'type'=>'melee',
        ],
        [
            'name'=>'Slugga',
            'a'=>'4',
            'bs-ws'=>'4+',
            'd'=>'3/4',
            'type'=>'ranged',
        ],
        [
            'name'=>'Choppa',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'4/5',
            'type'=>'melee',
        ],
        [
            'name'=>'Throwing knives',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'2/5',
            'type'=>'ranged',
        ],
        [
            'name'=>'Twin choppas',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'4/5',
            'type'=>'melee',
        ],
        [
            'name'=>'Breacha ram',
            'a'=>'3',
            'bs-ws'=>'3+',
            'd'=>'5/5',
            'type'=>'melee',
        ],
        [
            'name'=>'Scoped big shoota',
            'a'=>'6',
            'bs-ws'=>'3+',
            'd'=>'2/2',
            'type'=>'ranged',
        ],
        [
            'name'=>'Fists',
            'a'=>'3',
            'bs-ws'=>'3+',
            'd'=>'3/4',
            'type'=>'melee',
        ],
        [
            'name'=>'Dakka shoota',
            'a'=>'5',
            'bs-ws'=>'4+',
            'd'=>'3/4',
            'type'=>'ranged',
        ],
        [
            'name'=>'Shokka pistol',
            'a'=>'6',
            'bs-ws'=>'4+',
            'd'=>'1/1',
            'type'=>'ranged',
        ],
        [
            'name'=>'Burna',
            'a'=>'5',
            'bs-ws'=>'2+',
            'd'=>'2/2',
            'type'=>'ranged',
        ],
        [
            'name'=>'Rokkit launcha',
            'a'=>'5',
            'bs-ws'=>'4+',
            'd'=>'4/5',
            'type'=>'ranged',
        ],
        [
            'name'=>'Grot choppa',
            'a'=>'3',
            'bs-ws'=>'5+',
            'd'=>'1/4',
            'type'=>'melee',
        ],
        [
            'name'=>'Big choppa',
            'a'=>'4',
            'bs-ws'=>'2+',
            'd'=>'5/6',
            'type'=>'melee',
        ],
        [
            'name'=>'Power klaw',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'5/7',
            'type'=>'melee',
        ],
        [
            'name'=>'Dynamite',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'4/6',
            'type'=>'ranged',
        ],
        [
            'name'=>'Vicious bite',
            'a'=>'3',
            'bs-ws'=>'4+',
            'd'=>'4/5',
            'type'=>'melee',
        ],
        [
            'name'=>'Pulse carbine',
            'a'=>'4',
            'bs-ws'=>'4+',
            'd'=>'4/5',
            'type'=>'ranged',
        ],
        [
            'name'=>'Fists',
            'a'=>'3',
            'bs-ws'=>'5+',
            'd'=>'2/3',
            'type'=>'melee',
        ],
        [
            'name'=>'Suppressed pulse carbine',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'4/5',
            'type'=>'ranged',
        ],
        [
            'name'=>'Bionic arm',
            'a'=>'3',
            'bs-ws'=>'4+',
            'd'=>'3/4',
            'type'=>'melee',
        ],
        [
            'name'=>'Ion rifle standard',
            'a'=>'5',
            'bs-ws'=>'4+',
            'd'=>'4/5',
            'type'=>'ranged',
        ],
        [
            'name'=>'Ion rifle overcharge',
            'a'=>'5',
            'bs-ws'=>'4+',
            'd'=>'5/6',
            'type'=>'ranged',
        ],
        [
            'name'=>'Rail rifle',
            'a'=>'4',
            'bs-ws'=>'4+',
            'd'=>'4/4',
            'type'=>'ranged',
        ],
        [
            'name'=>'Marksman rail rifle standard',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'4/4',
            'type'=>'ranged',
        ],
        [
            'name'=>'Marksman rail rifle dart round',
            'a'=>'4',
            'bs-ws'=>'3+',
            'd'=>'3/3',
            'type'=>'ranged',
        ],
        [
            'name'=>'Burst cannon',
            'a'=>'6',
            'bs-ws'=>'4+',
            'd'=>'3/4',
            'type'=>'ranged',
        ],
        [
            'name'=>'Ram',
            'a'=>'3',
            'bs-ws'=>'5+',
            'd'=>'3/4',
            'type'=>'melee',
        ],
        [
            'name'=>'Twin pulse carbine',
            'a'=>'4',
            'bs-ws'=>'4+',
            'd'=>'4/5',
            'type'=>'ranged',
        ],
     ];

    public function run(): void
    {
        //
        foreach ($this->weapons as $weapon) {
            $w= new Weapon();
            $w->name=$weapon['name'];
            $w->a=$weapon['a'];
            $w->bs_ws=$weapon['bs-ws'];
            $w->d=$weapon['d'];
            $w->type=$weapon['type'];
            $w->save();
        }
        $this->command->info('Weapons created with data success!');
    }
}
